import { Area, Library } from "./types";

export const AREAS: Area[] = [
  {
    id: "frontend",
    name: "Frontend",
    count: 0,
    categories: [
      { id: "frameworks", name: "Frameworks", count: 0 },
      { id: "ui-components", name: "UI Components", count: 0 },
      { id: "css-styling", name: "CSS & Styling", count: 0 },
      { id: "animation", name: "Animation", count: 0 },
      { id: "3d-graphics", name: "3D & Graphics", count: 0 },
      { id: "state-management", name: "State Management", count: 0 },
      { id: "forms-validation", name: "Forms & Validation", count: 0 },
      { id: "data-fetching", name: "Data Fetching", count: 0 },
      { id: "charts", name: "Charts", count: 0 },
      { id: "maps", name: "Maps", count: 0 },
      { id: "editors", name: "Editors", count: 0 },
    ],
  },
  {
    id: "backend",
    name: "Backend",
    count: 0,
    categories: [
      { id: "web-frameworks", name: "Web Frameworks", count: 0 },
      { id: "db-orms", name: "ORMs & DB Clients", count: 0 },
      { id: "auth-security", name: "Auth & Security", count: 0 },
      { id: "api-utilities", name: "API Utilities", count: 0 },
    ],
  },
  {
    id: "database",
    name: "Database & Data",
    count: 0,
    categories: [
      { id: "postgres-clients", name: "PostgreSQL Clients", count: 0 },
      { id: "key-value", name: "Key-Value Stores", count: 0 },
      { id: "document-dbs", name: "Document Databases", count: 0 },
    ],
  },
  {
    id: "ai-ml",
    name: "AI & ML",
    count: 0,
    categories: [
      { id: "neural-networks", name: "Neural Networks", count: 0 },
      { id: "llm-frameworks", name: "LLM Frameworks", count: 0 },
      { id: "nlp-utilities", name: "NLP Utilities", count: 0 },
    ],
  },
  {
    id: "mobile",
    name: "Mobile",
    count: 0,
    categories: [
      { id: "cross-platform", name: "Cross-Platform", count: 0 },
      { id: "native-wrappers", name: "Native Wrappers", count: 0 },
    ],
  },
  {
    id: "testing",
    name: "Testing & QA",
    count: 0,
    categories: [
      { id: "unit-testing", name: "Unit Testing", count: 0 },
      { id: "e2e-testing", name: "E2E Testing", count: 0 },
    ],
  },
  {
    id: "devops",
    name: "DevOps & Cloud",
    count: 0,
    categories: [
      { id: "containerization", name: "Containerization", count: 0 },
      { id: "ci-cd-helpers", name: "CI/CD Helpers", count: 0 },
    ],
  },
  {
    id: "dev-tools",
    name: "Developer Tools",
    count: 0,
    categories: [
      { id: "linters-formatters", name: "Linters & Formatters", count: 0 },
      { id: "build-tools", name: "Build Tools", count: 0 },
    ],
  },
];

export const LIBRARIES: Library[] = [
  // Frontend -> Frameworks
  {
    id: "react",
    name: "React",
    description:
      "Component-based UI library for creating responsive web pages.",
    area: "frontend",
    category: "frameworks",
    ecosystem: "npm",
    packageName: "react",
    status: "active",
    latestVersion: "19.0.0",
    lastUpdated: "12d ago",
    installed: false,
  },
  {
    id: "next",
    name: "Next.js",
    description:
      "The React Framework for high-performance server-side rendered apps.",
    area: "frontend",
    category: "frameworks",
    ecosystem: "npm",
    packageName: "next",
    status: "active",
    latestVersion: "15.1.6",
    lastUpdated: "3d ago",
    installed: false,
  },
  {
    id: "vue",
    name: "Vue",
    description:
      "Progressive, approachable framework for building web interfaces.",
    area: "frontend",
    category: "frameworks",
    ecosystem: "npm",
    packageName: "vue",
    status: "active",
    latestVersion: "3.4.0",
    lastUpdated: "1mo ago",
    installed: false,
  },
  {
    id: "svelte",
    name: "Svelte",
    description:
      "Cybernetic compilation framework for building user interfaces.",
    area: "frontend",
    category: "frameworks",
    ecosystem: "npm",
    packageName: "svelte",
    status: "active",
    latestVersion: "4.2.8",
    lastUpdated: "2mo ago",
    installed: false,
  },

  // Frontend -> UI Components
  {
    id: "shadcn",
    name: "Shadcn UI",
    description:
      "Beautifully designed accessible components that you can copy and paste into your apps.",
    area: "frontend",
    category: "ui-components",
    ecosystem: "npm",
    packageName: "shadcn",
    status: "active",
    latestVersion: "3.6.2",
    lastUpdated: "1d ago",
    installed: false,
  },
  {
    id: "radix-ui",
    name: "Radix UI Primitives",
    description:
      "Unstyled, accessible component primitives for building custom React design systems.",
    area: "frontend",
    category: "ui-components",
    ecosystem: "npm",
    packageName: "radix-ui",
    status: "active",
    latestVersion: "1.4.3",
    lastUpdated: "1wk ago",
    installed: false,
  },
  {
    id: "@mui/material",
    name: "Material UI",
    description:
      "React UI components that implement Google's Material Design guidelines.",
    area: "frontend",
    category: "ui-components",
    ecosystem: "npm",
    packageName: "@mui/material",
    status: "active",
    latestVersion: "5.15.0",
    lastUpdated: "5d ago",
    installed: false,
  },

  // Frontend -> CSS & Styling
  {
    id: "tailwindcss",
    name: "Tailwind CSS",
    description: "A utility-first CSS framework for rapid UI styling.",
    area: "frontend",
    category: "css-styling",
    ecosystem: "npm",
    packageName: "tailwindcss",
    status: "active",
    latestVersion: "4.0.0",
    lastUpdated: "5d ago",
    installed: false,
  },
  {
    id: "sass",
    name: "Sass",
    description:
      "Sass is a mature, stable, and powerful professional grade CSS extension language.",
    area: "frontend",
    category: "css-styling",
    ecosystem: "npm",
    packageName: "sass",
    status: "active",
    latestVersion: "1.70.0",
    lastUpdated: "2wk ago",
    installed: false,
  },

  // Frontend -> Animation
  {
    id: "framer-motion",
    name: "Framer Motion",
    description: "An open-source production-ready motion library for React.",
    area: "frontend",
    category: "animation",
    ecosystem: "npm",
    packageName: "framer-motion",
    status: "active",
    latestVersion: "11.0.3",
    lastUpdated: "2d ago",
    installed: false,
  },
  {
    id: "gsap",
    name: "GSAP",
    description: "Professional-grade JavaScript animation for the modern web.",
    area: "frontend",
    category: "animation",
    ecosystem: "npm",
    packageName: "gsap",
    status: "active",
    latestVersion: "3.15.0",
    lastUpdated: "3d ago",
    installed: false,
  },

  // Frontend -> 3D & Graphics
  {
    id: "three",
    name: "Three.js",
    description: "3D rendering library for interactive WebGL experiences.",
    area: "frontend",
    category: "3d-graphics",
    ecosystem: "npm",
    packageName: "three",
    status: "active",
    latestVersion: "0.160.0",
    lastUpdated: "6d ago",
    installed: false,
  },
  {
    id: "@react-three/fiber",
    name: "React Three Fiber",
    description: "React renderer for building Three.js scenes declaratively.",
    area: "frontend",
    category: "3d-graphics",
    ecosystem: "npm",
    packageName: "@react-three/fiber",
    status: "active",
    latestVersion: "8.15.12",
    lastUpdated: "3d ago",
    installed: false,
  },
  {
    id: "babylonjs",
    name: "Babylon.js",
    description: "Feature-rich web 3D engine.",
    area: "frontend",
    category: "3d-graphics",
    ecosystem: "npm",
    packageName: "babylonjs",
    status: "active",
    latestVersion: "6.35.0",
    lastUpdated: "12d ago",
    installed: false,
  },
  {
    id: "legacy3d",
    name: "Legacy3D",
    description: "Older WebGL abstraction.",
    area: "frontend",
    category: "3d-graphics",
    ecosystem: "npm",
    packageName: "legacy3d",
    status: "deprecated",
    deprecated: true,
    replacement: "three",
    latestVersion: "0.2.1",
    lastUpdated: "4yr ago",
    installed: false,
  },

  // Frontend -> State Management
  {
    id: "@reduxjs/toolkit",
    name: "Redux Toolkit",
    description:
      "The official, opinionated, batteries-included toolset for efficient Redux development.",
    area: "frontend",
    category: "state-management",
    ecosystem: "npm",
    packageName: "@reduxjs/toolkit",
    status: "active",
    latestVersion: "2.1.0",
    lastUpdated: "1mo ago",
    installed: false,
  },
  {
    id: "zustand",
    name: "Zustand",
    description:
      "A small, fast, and scalable bearbones state-management solution.",
    area: "frontend",
    category: "state-management",
    ecosystem: "npm",
    packageName: "zustand",
    status: "active",
    latestVersion: "4.5.0",
    lastUpdated: "1wk ago",
    installed: false,
  },

  // Frontend -> Forms & Validation
  {
    id: "zod",
    name: "Zod",
    description: "TypeScript-first schema declaration and validation library.",
    area: "frontend",
    category: "forms-validation",
    ecosystem: "npm",
    packageName: "zod",
    status: "active",
    latestVersion: "3.22.4",
    lastUpdated: "8d ago",
    installed: false,
  },
  {
    id: "react-hook-form",
    name: "React Hook Form",
    description:
      "Performant, flexible and extensible forms with easy-to-use validation.",
    area: "frontend",
    category: "forms-validation",
    ecosystem: "npm",
    packageName: "react-hook-form",
    status: "active",
    latestVersion: "7.49.3",
    lastUpdated: "6d ago",
    installed: false,
  },

  // Frontend -> Data Fetching
  {
    id: "@tanstack/react-query",
    name: "TanStack Query",
    description: "Declarative, dependency-free data fetching & caching.",
    area: "frontend",
    category: "data-fetching",
    ecosystem: "npm",
    packageName: "@tanstack/react-query",
    status: "active",
    latestVersion: "5.15.0",
    lastUpdated: "2d ago",
    installed: false,
  },
  {
    id: "axios",
    name: "Axios",
    description: "Promise based HTTP client for the browser and node.js.",
    area: "frontend",
    category: "data-fetching",
    ecosystem: "npm",
    packageName: "axios",
    status: "active",
    latestVersion: "1.6.5",
    lastUpdated: "1mo ago",
    installed: false,
  },

  // Frontend -> Charts
  {
    id: "recharts",
    name: "Recharts",
    description: "Redefined chart library built with React and D3.",
    area: "frontend",
    category: "charts",
    ecosystem: "npm",
    packageName: "recharts",
    status: "active",
    latestVersion: "2.15.4",
    lastUpdated: "4d ago",
    installed: false,
  },

  // Frontend -> Maps
  {
    id: "maplibre-gl",
    name: "MapLibre GL",
    description: "Open-source vector map rendering library based on WebGL.",
    area: "frontend",
    category: "maps",
    ecosystem: "npm",
    packageName: "maplibre-gl",
    status: "active",
    latestVersion: "5.15.0",
    lastUpdated: "1wk ago",
    installed: false,
  },

  // Frontend -> Editors
  {
    id: "monaco-editor",
    name: "Monaco Editor",
    description: "The browser-based code editor that powers VS Code.",
    area: "frontend",
    category: "editors",
    ecosystem: "npm",
    packageName: "monaco-editor",
    status: "active",
    latestVersion: "0.45.0",
    lastUpdated: "2mo ago",
    installed: false,
  },

  // Backend -> Web Frameworks
  {
    id: "fastapi",
    name: "FastAPI",
    description:
      "High performance Python web framework, easy to learn, fast to code.",
    area: "backend",
    category: "web-frameworks",
    ecosystem: "pypi",
    packageName: "fastapi",
    status: "active",
    latestVersion: "0.115.0",
    lastUpdated: "4d ago",
    installed: false,
  },
  {
    id: "django",
    name: "Django",
    description: "The Python web framework for perfectionists with deadlines.",
    area: "backend",
    category: "web-frameworks",
    ecosystem: "pypi",
    packageName: "django",
    status: "maintenance",
    latestVersion: "5.0.1",
    lastUpdated: "2mo ago",
    installed: false,
  },
  {
    id: "express",
    name: "Express.js",
    description: "Fast, unopinionated, minimalist web framework for Node.js.",
    area: "backend",
    category: "web-frameworks",
    ecosystem: "npm",
    packageName: "express",
    status: "maintenance",
    latestVersion: "5.0.0",
    lastUpdated: "1mo ago",
    installed: false,
  },

  // Backend -> ORMs
  {
    id: "prisma",
    name: "Prisma",
    description:
      "Next-generation Node.js and TypeScript ORM for Postgres, MySQL, SQLite, and MongoDB.",
    area: "backend",
    category: "db-orms",
    ecosystem: "npm",
    packageName: "prisma",
    status: "active",
    latestVersion: "5.7.0",
    lastUpdated: "6d ago",
    installed: false,
  },
  {
    id: "sqlalchemy",
    name: "SQLAlchemy",
    description:
      "The Database Toolkit and Object Relational Mapper for Python.",
    area: "backend",
    category: "db-orms",
    ecosystem: "pypi",
    packageName: "sqlalchemy",
    status: "active",
    latestVersion: "2.0.25",
    lastUpdated: "1wk ago",
    installed: false,
  },

  // Backend -> Auth & Security
  {
    id: "better-auth",
    name: "Better Auth",
    description: "Next-generation TypeScript-first authentication solution.",
    area: "backend",
    category: "auth-security",
    ecosystem: "npm",
    packageName: "better-auth",
    status: "active",
    latestVersion: "1.0.4",
    lastUpdated: "1d ago",
    installed: false,
  },
  {
    id: "old-auth",
    name: "Old Auth",
    description: "Legacy authentication middleware.",
    area: "backend",
    category: "auth-security",
    ecosystem: "npm",
    packageName: "old-auth",
    status: "deprecated",
    deprecated: true,
    replacement: "better-auth",
    latestVersion: "0.0.8",
    lastUpdated: "5yr ago",
    installed: false,
  },

  // Database -> Key-Value
  {
    id: "redis",
    name: "Redis",
    description: "Python client for Redis key-value store database.",
    area: "database",
    category: "key-value",
    ecosystem: "pypi",
    packageName: "redis",
    status: "active",
    latestVersion: "5.0.1",
    lastUpdated: "2mo ago",
    installed: false,
  },

  // Database -> Document DBs
  {
    id: "mongoose",
    name: "Mongoose",
    description:
      "MongoDB object modeling tool designed to work in an asynchronous environment.",
    area: "database",
    category: "document-dbs",
    ecosystem: "npm",
    packageName: "mongoose",
    status: "active",
    latestVersion: "9.4.1",
    lastUpdated: "1d ago",
    installed: false,
  },

  // AI & ML -> Neural Networks
  {
    id: "torch",
    name: "PyTorch",
    description:
      "Tensors and Dynamic neural networks in Python with strong GPU acceleration.",
    area: "ai-ml",
    category: "neural-networks",
    ecosystem: "pypi",
    packageName: "torch",
    status: "active",
    latestVersion: "2.1.2",
    lastUpdated: "10d ago",
    installed: false,
  },

  // AI & ML -> LLM Frameworks
  {
    id: "langchain",
    name: "LangChain",
    description: "Building applications with LLMs through composability.",
    area: "ai-ml",
    category: "llm-frameworks",
    ecosystem: "pypi",
    packageName: "langchain",
    status: "active",
    latestVersion: "0.1.0",
    lastUpdated: "1d ago",
    installed: false,
  },

  // Testing -> Unit Testing
  {
    id: "jest",
    name: "Jest",
    description:
      "Delightful JavaScript Testing Framework with a focus on simplicity.",
    area: "testing",
    category: "unit-testing",
    ecosystem: "npm",
    packageName: "jest",
    status: "active",
    latestVersion: "29.7.0",
    lastUpdated: "2mo ago",
    installed: false,
  },

  // DevOps -> Containerization
  {
    id: "docker",
    name: "Docker CLI",
    description:
      "Automate app deployment inside lightweight, portable software containers.",
    area: "devops",
    category: "containerization",
    ecosystem: "cargo", // dummy but mapping to show crates or other
    packageName: "docker",
    status: "active",
    latestVersion: "24.0.7",
    lastUpdated: "1mo ago",
    installed: false,
  },

  // Developer Tools -> Linters
  {
    id: "eslint",
    name: "ESLint",
    description: "Find and fix problems in your JavaScript/TypeScript code.",
    area: "dev-tools",
    category: "linters-formatters",
    ecosystem: "npm",
    packageName: "eslint",
    status: "active",
    latestVersion: "10.2.1",
    lastUpdated: "3d ago",
    installed: false,
  },
  {
    id: "prettier",
    name: "Prettier",
    description: "An opinionated code formatter supporting many languages.",
    area: "dev-tools",
    category: "linters-formatters",
    ecosystem: "npm",
    packageName: "prettier",
    status: "active",
    latestVersion: "3.2.4",
    lastUpdated: "1wk ago",
    installed: false,
  },

  // Developer Tools -> Build Tools
  {
    id: "vite",
    name: "Vite",
    description: "Next generation frontend tooling. It's fast.",
    area: "dev-tools",
    category: "build-tools",
    ecosystem: "npm",
    packageName: "vite",
    status: "active",
    latestVersion: "8.0.10",
    lastUpdated: "1d ago",
    installed: false,
  },
];
